sfdx-project/force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-project/src/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Room 1</fullName>
            </value>
            <value>
                <fullName>Room 2</fullName>
            </value>
            <value>
                <fullName>Room 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

review/sfdx-project/force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SSP-{0000}</displayFormat>
        <label>Session Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-project/force-app/main/default/objects/Session_Speaker__c/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-project/force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-project/force-app/main/default/objects/Session_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Session Speakers</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-project/force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-project/force-app-completed/main/default/classes/SessionController.cls
public with sharing class SessionController {

    /**
    * Retrieve all sessions
    * In a prod environment, the operation should be paginated dynamically
    * and the filtering should be done here rather than on the client side
    */
    @AuraEnabled(cacheable=true)
    public static List<Session__c> getSessions() {
        return [SELECT Id, Name, Date_and_Time__c FROM Session__c LIMIT 100];
    }

    /**
    * Retrieve a session with its speakers or null if session is not found.
    * @param sessionId
    */
    @AuraEnabled(cacheable=true)
    public static Session__c getSessionWithSpeakers(Id sessionId) {
        List<Session__c> sessions = [SELECT Id, Name, Room__c, Description__c, Date_and_Time__c, 
                (SELECT Speaker__r.Id, Speaker__r.First_Name__c, Speaker__r.Last_Name__c, Speaker__r.Bio__c, Speaker__r.Email__c FROM Session_Speakers__r) 
                FROM Session__c WHERE Id = :sessionId];
        if (sessions.size() == 0) {
            return null;
        }
        return sessions.get(0);
    }
}